name: Rust

on:
  push:
    branches: ["master", "unstable"]
  pull_request:
    branches: ["master", "unstable"]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install stable toolchain (fmt, clippy)
        run: rustup toolchain install stable --profile minimal -c rustfmt,clippy

      - name: Format check
        run: make fmt_check

      - name: Clippy check
        run: make clippy

  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install stable toolchain (fmt, clippy)
        run: rustup toolchain install stable --profile minimal -c rustfmt,clippy

      - name: Build
        run: make build

      - name: Run tests
        run: make test
